# Github workflow to compile latex and deploy the pdf to an orphan branch.
# The latest compiled pdf is made available at e.g.
# https://github.com/fdesanti/reponame/blob/build/filename.pdf
# Davide Gerosa (2021) https://github.com/dgerosa

name: writeapaper

permissions:
  contents: write #set github action priviledge

on: [push]
env:
  # Adjust these if needed
  DIR: draft
  FILE: draft
jobs:
  paper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      #- name: Install TeXlive
      #  run: sudo apt-get update && sudo apt-get install texlive texlive-publishers texlive-science latexmk cm-super
      #- name: LaTeX compile
      #  working-directory: ${{ env.DIR }}
      #  #run: latexmk -pdf -bibtex ${{ env.FILE }}
      #  run: pdflatex ${{ env.FILE }}; bibtex ${{ env.FILE }}; pdflatex ${{ env.FILE }}; pdflatex ${{ env.FILE }};
      - name: LaTeX
        uses: xu-cheng/texlive-action@v2
        with:
          run: |
              cd ${{ env.DIR }}
              pdflatex ${{ env.FILE }}
              bibtex ${{ env.FILE }}
              pdflatex ${{ env.FILE }}
              pdflatex ${{ env.FILE }}
      - name: move
        run: |
            mkdir -p github_artifacts
            mv ${{ env.DIR }}/${{ env.FILE }}.pdf ./github_artifacts/
      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FILE }}.pdf
          path: ./github_artifacts

  update-readme:
    needs: [paper]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}  # assumes the push was to your main branch
      - name: Update README with deployment info
        run: |
          # Extract the repository name from "owner/repo"
          repo=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
          # Write the new README with the required structure:
          printf "# %s\n\nThe compiled pdf is available [here](https://github.com/%s/blob/build/%s.pdf)\n" "$repo" "$GITHUB_REPOSITORY" "$FILE" > README.md
      - name: Commit and push updated README
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          # Use "[skip ci]" to prevent recursive workflow triggers
          git commit -m "Update README with compiled PDF link [skip ci]" || echo "No changes to commit"
          git push origin ${{ github.ref }}

  deploy:
    # Edit here if compiling multiple papers
    needs: [paper]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v4
        with:
          path: github_artifacts

      - name: move
        run: |
            mkdir -p github_deploy
            mv github_artifacts/*/* github_deploy

      - name: deploy on orphan branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: build
          force_orphan: true

  clean:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - name: delete
        uses: geekyeggo/delete-artifact@v4
        with:
          name: '*.pdf'
